# Default values for cinder.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image_repository: DEFINED-IN-REGION-CHART
  image_namespace: DEFINED-IN-REGION-CHART
  cinder_api_port_internal: '8776'

image_version_cinder_api_m3: 'v1'
image_version_cinder_scheduler: 'v1'

debug: "True"

db_name: cinder
db_user: cinder
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn_key: DEFINE-IN-REGION-CHART


volumes_vmware:
  - name: DEFINED-IN-REGION-CHART
    username: DEFINED-IN-REGION-CHART
    password: DEFINED-IN-REGION-CHART
    host: DEFINED-IN-REGION-CHART
    availability_zone: DEFINED-IN-REGION-CHART
volumes_netapp:
  - name: DEFINED-IN-REGION-CHART
    username: DEFINED-IN-REGION-CHART
    password: DEFINED-IN-REGION-CHART
    host: DEFINED-IN-REGION-CHART
    vserver: DEFINED-IN-REGION-CHART
    availability_zone: DEFINED-IN-REGION-CHART

postgres:
  name: cinder
