# Default values for cinder.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
global:
  image_repository: DEFINED-IN-REGION-CHART
  image_namespace: DEFINED-IN-REGION-CHART
  cinder_api_port_internal: '8776'

  hypervisors_vmware: []
  #  - name: DEFINED-IN-REGION-CHART
  #    username: DEFINED-IN-REGION-CHART
  #    password: DEFINED-IN-REGION-CHART
  #    host: DEFINED-IN-REGION-CHART
  #    availability_zone: DEFINED-IN-REGION-CHART
  volumes_netapp: []
  #  - name: DEFINED-IN-REGION-CHART
  #    username: DEFINED-IN-REGION-CHART
  #    password: DEFINED-IN-REGION-CHART
  #    host: DEFINED-IN-REGION-CHART
  #    vserver: DEFINED-IN-REGION-CHART
  #    availability_zone: DEFINED-IN-REGION-CHART
  volumes: []
  osprofiler: {}
  pgbouncer:
    enabled: false

osprofiler: {}

image_version_cinder_api: 'v1'
image_version_cinder_scheduler: 'v1'
image_version_cinder_volume: 'v1'

pod:
  replicas:
    api: 2
    scheduler: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 5
        pod_replacement_strategy: RollingUpdate
        rolling_update:
           max_unavailable: 0
           max_surge: 1

jobs:
  db_purge:
    cron: # "0 8 * * * 1"
    max_rows: 0

debug: "True"

db_name: cinder
db_user: cinder
db_password: DEFINED-IN-REGION-CHART

port_metrics: '9102'

sentry_dsn: DEFINE-IN-REGION-CHART

pg_metrics:
  name: cinder
  db_name: cinder
  db_user: cinder
  db_password: DEFINED-IN-REGION-CHART
  customMetrics:
    openstack_stuck_volumes:
      query: "SELECT host, project_id, availability_zone, status, COUNT(*) FILTER (WHERE updated_at < now() - interval '15 minutes') AS count_gauge, MAX(EXTRACT(epoch FROM now() - updated_at)) AS max_duration_gauge FROM volumes WHERE status IN ('attaching', 'deleting', 'detaching') GROUP BY host, availability_zone, volume_type_id, status, project_id"
      metrics:
        - host:
            usage: "LABEL"
            description: "Name of the host"
        - availability_zone:
            usage: "LABEL"
            description: "Availability Zone of the Volume"
        - project_id:
            usage: "LABEL"
            description: "Project ID"
        - status:
            usage: "LABEL"
            description: "Status of the volume"
        - count_gauge:
            usage: "GAUGE"
            description: "Number of volumes"
        - max_duration_gauge:
            usage: "GAUGE"
            description: "Maximum duration of state"
    openstack_volumes:
      query: "SELECT host, availability_zone, volume_type_id, project_id, status, attach_status, COUNT(*) AS count_gauge, SUM(size) size_gauge FROM volumes GROUP BY host, availability_zone, volume_type_id, project_id, status, attach_status"
      metrics:
        - host:
            usage: "LABEL"
            description: "Name of the host"
        - availability_zone:
            usage: "LABEL"
            description: "Availability Zone of the Volume"
        - volume_type_id:
            usage: "LABEL"
            description: "Type of the volume"
        - project_id:
            usage: "LABEL"
            description: "ID of the Project"
        - status:
            usage: "LABEL"
            description: "Status of the volume"
        - attach_status:
            usage: "LABEL"
            description: "Status of the attachment"
        - count_gauge:
            usage: "GAUGE"
            description: "Number of volumes"
        - size_gauge:
            usage: "GAUGE"
            description: "Size of volumes"
    openstack_snapshots:
      query: "select snapshots.status, snapshots.project_id, volumes.host, COUNT(*) AS count_gauge, SUM(volume_size) size_gauge from snapshots join volumes on snapshots.volume_id=volumes.id GROUP BY snapshots.status, snapshots.project_id, volumes.host"
      metrics:
        - project_id:
            usage: "LABEL"
            description: "ID of the Project"
        - host:
            usage: "LABEL"
            description: "Name of the host"
        - status:
            usage: "LABEL"
            description: "Status of the Snapshot"
        - count_gauge:
            usage: "GAUGE"
            description: "Number of Snapshots"
        - size_gauge:
            usage: "GAUGE"
            description: "Size of Snapshots"
postgres:
  name: cinder

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
            formatter: context
        "null":
            class: logging.NullHandler
            args: "()"
            formatter: default
        sentry:
            class: raven.handlers.logging.SentryHandler
            level: ERROR
            args: "()"
    loggers:
        root:
            handlers: stdout, sentry
            level: WARNING
        cinder:
            handlers: stdout, sentry
            level: DEBUG
        taskflow:
            handlers: stdout, sentry
            level: DEBUG
        eventlet.wsgi.server:
            handlers: stdout, sentry
            level: INFO
        sqlalchemy:
            handlers: stdout, sentry
            level: WARNING
        suds:
            handlers: "null"
            level: ERROR
