kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ad-healthcheck
  labels:
    system: openstack
    type: healthcheck
    component: keystone
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      name: ad-healthcheck


  template:
    metadata:
      labels:
        name: ad-healthcheck
      annotations:
        chart-version: {{.Chart.Version}}
    spec:
      containers:
        - name: ad-healthcheck
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ad-healthcheck:{{.Values.image_version_ad_healthcheck}}
          imagePullPolicy: IfNotPresent
          args:
            - -web.listen-address=0.0.0.0:9101
            - -namespace=ad
            - checks/*
          env:
            - name: AD_DNS
              value: {{.Values.ad_dns}}
            - name: AD_BIND_DN
              value: {{.Values.ad_ldap_user}}
            - name: AD_BIND_SECRET
              value: {{.Values.ad_ldap_password}}
            - name: AD_SUFFIX_OU
              value: {{.Values.ad_ldap_suffix}}
            - name: AD_NODE_1
              value: {{.Values.ad_node_1}}
            - name: AD_NODE_2
              value: {{.Values.ad_node_2}}
            - name: AD_TEST_GROUP
              value: {{.Values.ad_test_group}}
            - name: AD_TEST_USER
              value: {{.Values.ad_test_user}}
            - name: CAM_DNS
              value: {{.Values.cam_dns}}
            - name: EWS_DNS
              value: {{.Values.ews_dns}}
          ports:
            - name: metrics
              containerPort: {{.Values.port_metrics}}