apiVersion: v1
kind: ConfigMap
metadata:
  name: barbican-etc
  labels:
    system: openstack
    type: configuration
    component: barbican
data:
  barbican-api-paste.ini: |
{{ include (print .Template.BasePath "/etc/_barbican-api-paste.ini.tpl") . | indent 4 }}
  barbican.conf: |
{{ include (print .Template.BasePath "/etc/_barbican.conf.tpl") . | indent 4 }}
  policy.json: |
{{ include (print .Template.BasePath "/etc/_policy.json.tpl") . | indent 4 }}
  logging.ini: |
{{ include "loggerIni" .Values.logging | indent 4 }}
