kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: manila-api
  labels:
    system: openstack
    type: api
    component: manila
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: manila-api
  template:
    metadata:
      labels:
        name: manila-api
    spec:
      containers:
        - name: manila-api
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-manila-api-m3:{{.Values.image_version_manila_api_m3}}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/manila-api-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "manila-migration"
            - name: DEPENDENCY_SERVICE
              value: "postgres-manila,rabbitmq"
            - name: DEBUG_CONTAINER
              value: "false"
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.manila_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: manila-api
              containerPort: {{.Values.global.manila_api_port_internal}}
          volumeMounts:
            - mountPath: /manila-etc
              name: manila-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: manila-etc
          configMap:
            name: manila-etc
        - name: container-init
          configMap:
            name: manila-bin
