apiVersion: v1
kind: ConfigMap
metadata:
  name: manila-etc
  labels:
    system: openstack
    type: configuration
    component: manila

data:
  manila.conf: |
{{ include (print .Template.BasePath "/etc/_manila.conf.tpl") . | indent 4 }}
  api-paste.ini: |
{{ include (print .Template.BasePath "/etc/_api-paste.ini.tpl") . | indent 4 }}
  policy.json: |
{{ include (print .Template.BasePath "/etc/_manila-policy.json.tpl") . | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
