{{- if .Values.inspector.ip  }}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: inspector
    component: ironic
  {{- if .Values.vice_president }}
  annotations:
    vice-president: "true"
  {{- end }}
spec:
  tls:
    - secretName: tls-{{ include "ironic_inspector_endpoint_host_public" . | replace "." "-" }}
      hosts: [{{include "ironic_inspector_endpoint_host_public" .}}]
  rules:
    - host: {{include "ironic_inspector_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: ironic-inspector
            servicePort: {{.Values.inspector.port_internal}}
{{- end }}
