{{- if .Values.image_version_ironic_inspector -}}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: backend
    component: none
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: ironic-inspector
  template:
    metadata:
      labels:
        name: ironic-inspector
    spec:
      containers:
        - name: ironic-inspector
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-ironic-inspector:{{.Values.image_version_ironic_inspector}}
          imagePullPolicy: IfNotPresent
          env:
            - name: COMMAND
              value: "ironic-inspector --config-file /var/lib/kolla/config_files/ironic.conf"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "ironic-api,rabbitmq"
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          volumeMounts:
            - mountPath: /var/lib/kolla/config_files
              name: ironic-inspector-etc
            - mountPath: /ironic-patches
              name: ironic-patches
{{- if .Values.image_version_staticdhcpd}}
        - name: dhcp
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-staticdhcpd:{{.Values.image_version_staticdhcpd}}
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          ports:
            - name: dhcp
              protocol: UDP
              containerPort: {{.Values.inspector.dhcp.port}}
            - name: dhcp-proxy
              protocol: UDP
              containerPort: {{.Values.inspector.dhcp.proxy_port}}
          volumeMounts:
            - name: dhcp-config
              mountPath: /var/lib/kolla/config_files
{{- end }}
      volumes:
        - name: ironic-inspector-etc
          configMap:
            name: ironic-inspector-etc
        - name: ironic-patches
          configMap:
            name: ironic-patches
{{- if .Values.image_version_staticdhcpd }}
        - name: dhcp-config
          configMap:
            name: ironic-inspector-dhcp
            defaultMode: 0400
{{ end -}}
{{ end -}}
