apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-inspector-etc
  labels:
    system: openstack
    type: configuration
    component: ironic

data:
  # Do not copy the config to /etc/ironic-inspector, as it will overwrite the rootwrap.conf stored in the image
  # Mode Read-execute, because we create a directory, and it takes the same permissions as the file
  config.json: |
    {"command": "kubernetes-entrypoint"}
  ironic.conf: |
{{ tuple "etc/_ironic_inspector.conf.tpl" . | include "template" | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
