apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-bin
  labels:
    system: openstack
    type: configuration
    component: keystone

data:
  common.sh: |
{{ include "common.sh" .| indent 4 }}
  keystone-bootstrap: |
{{ tuple "bin/_keystone-bootstrap.tpl" . | include "template" | indent 4 }}
  keystone-seed: |
{{ tuple "bin/_keystone-seed.tpl" . | include "template" | indent 4 }}
  keystone-start: |
{{ tuple "bin/_keystone-start.tpl" . | include "template" | indent 4 }}
