apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keystone-cron
  labels:
    system: openstack
    type: operations
    component: keystone
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keystone-cron
  template:
    metadata:
      labels:
        app: keystone-cron
      annotations:
        chart-version: {{.Chart.Version}}
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        configmap-bin-hash: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: cron
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-keystone:{{.Values.image_version_keystone}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/keystone-cron"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "keystone-migration,keystone-bootstrap"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
          volumeMounts:
            - mountPath: /keystone-etc
              name: keystone-etc
            - mountPath: /fernet-keys
              name: fernet-secret
              readOnly: true
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: fernet-secret
          secret:
            secretName: fernet-secret
        - name: container-init
          configMap:
            name: keystone-bin
            defaultMode: 0755
