kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: keystone
  labels:
    system: openstack
    type: api
    component: keystone
spec:
  minReadySeconds: 5
  replicas: {{ .Values.pod.replicas.api }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      name: keystone
  template:
    metadata:
      labels:
        name: keystone
{{ tuple . "keystone" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        configmap-bin-hash: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
{{- if and (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "5") }}
        scheduler.alpha.kubernetes.io/affinity: >
            {{ tuple . "keystone" "api" | include "kubernetes_pod_anti_affinity" }}
{{- end }}
    spec:
      containers:
        - name: keystone
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-keystone:{{.Values.image_version_keystone}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v3
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 15
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/keystone-start"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "keystone-migration,keystone-bootstrap"
            - name: DEPENDENCY_SERVICE
              value: "postgres-keystone,rabbitmq,memcached"
            - name: DEBUG_CONTAINER
              value: "false"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: STATSD_PREFIX
              value: "openstack"
          ports:
            - name: public
              containerPort: 5000
            - name: admin
              containerPort: 35357
          volumeMounts:
            - mountPath: /keystone-etc
              name: keystone-etc
            - mountPath: /fernet-keys
              name: fernet-secret
              readOnly: true
            - mountPath: /container.init
              name: container-init
        - name: statsd
          image: prom/statsd-exporter:master
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: fernet-secret
          secret:
            secretName: fernet-secret
        - name: container-init
          configMap:
            name: keystone-bin
            defaultMode: 0755
