apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: openstack-operator
  labels:
    system: openstack
    type: kubernetes-operator
    component: openstack-operator
      annotations:
        chart-version: {{.Chart.Version}}
        checksum/bin-configmap.conf: {{ include (print $.Chart.Name "/templates/bin-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: openstack-operator
  template:
    metadata:
      labels:
        name: openstack-operator
    spec:
      containers:
        - name: openstack-operator
          image: {{.Values.global.image_repository}}/monsoon/openstack-operator:{{.Values.image_version_openstack_operator}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/openstack-operator"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "keystone-migration,keystone-bootstrap"
            - name: DEPENDENCY_SERVICE
              value: "postgres-keystone,keystone"
          volumeMounts:
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: container-init
          configMap:
            name: keystone-bin
