apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: keystone-seeder
  labels:
    system: openstack
    type: backend
    component: keystone-seed
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: keystone-seeder
  template:
    metadata:
      labels:
        name: keystone-seeder
    spec:
      containers:
        - name: keystone-seeder
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-keystone-m3:{{.Values.image_version_keystone_m3}}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "bash /container.init/keystone-seed"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "keystone-migration,keystone-bootstrap"
            - name: DEPENDENCY_SERVICE
              value: "postgres-keystone,rabbitmq,keystone"
            - name: DEBUG_CONTAINER
          volumeMounts:
            - mountPath: /keystone-etc
              name: keystone-etc
            - mountPath: /keystone-config
              name: keystone-config
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: keystone-etc
          configMap:
            name: keystone-etc
        - name: keystone-config
          configMap:
            name: keystone-seed
            items:
              - key: keystone-seed.yaml
                path: keystone-seed.yaml
        - name: container-init
          configMap:
            name: keystone-bin
