apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-nova
  namespace: {{.Release.Namespace}}
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sh: |
    #!/usr/bin/env bash

    data_dir=/postgresql-data/data

    if [[ ! -e $data_dir ]]
    then
      mkdir $data_dir
    fi

    cp /postgresql-conf/postgresql.conf  $data_dir/postgresql.conf

    export PGUSER=postgres
    psql <<- EOSQL
        CREATE DATABASE {{.Values.db_name}};
        CREATE ROLE {{.Values.db_user}} WITH ENCRYPTED PASSWORD '{{.Values.db_password}}' LOGIN;
        GRANT ALL PRIVILEGES ON DATABASE {{.Values.db_name}} TO {{.Values.db_user}};

        CREATE DATABASE {{.Values.api_db_name}};
        CREATE ROLE {{.Values.api_db_user}} WITH ENCRYPTED PASSWORD '{{.Values.api_db_password}}' LOGIN;
        GRANT ALL PRIVILEGES ON DATABASE {{.Values.api_db_name}} TO {{.Values.api_db_user}};
    EOSQL



