# Default values for ironic.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
#
global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  ironic_api_port_internal: '6385'
  ironic_tftp_port_public: '69'
  osprofiler: {}
  fernet_router:
    image_version: 'latest'

osprofiler:
    enabled: false

pod:
  replicas:
    api: 2
    inspector: 1
    pxe: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 5
        pod_replacement_strategy: RollingUpdate
        rolling_update:
           max_unavailable: 0
           max_surge: 1

image_version_ironic_api:
image_version_ironic_conductor:
image_version_ironic_inspector:
image_version_ironic_pxe:
swift_multi_tenant: True

debug: "True"
db_name: ironic
db_user: ironic
db_password:

inspector_db_name: ironic_inspector
inspector_db_user: ironic_inspector
inspector_db_password:

api:
  override: {}

inspector:
  port_internal: '5050'
  dhcp:
    port: '67'
    proxy_port: '4011'
    ip: DEFINE_IN_REGION_CHART
    range: DEFINE_IN_REGION_CHART
    options:
      router: DEFINE_IN_REGION_CHART

conductor:
  hosts: []
  deploy:
    protocol: 'http'
    port: 8088

agent:
  deploy_logs:
    collect: "on_failure"
    storage_backend: "local"
    swift_days_to_expire: 30

console:
  secret:

tftp_ip:

port_metrics: '9102'
sentry_dsn: DEFINE_IN_REGION_CHART

network_management_uuid: DEFINE_IN_REGION_CHART
network_cleaning_uuid: DEFINE_IN_REGION_CHART
swift_account: DEFINE_IN_REGION_CHART
swift_tempurl: DEFINE_IN_REGION_CHART

pg_metrics:
  name: ironic
  db_name: ironic
  db_user: ironic
  db_password: DEFINED-IN-REGION-CHART

postgres:
  name: ironic

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
            formatter: context
        "null":
            class: logging.NullHandler
            args: "()"
            formatter: default
    loggers:
        root:
            handlers: stdout
            level: WARNING
        ironic:
            handlers: stdout
            level: DEBUG
        eventlet.wsgi.server:
            handlers: stdout
            level: INFO
