# Default values for ironic.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
#
global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  ironic_api_port_internal: '6385'
  ironic_tftp_port_public: '69'

image_version_ironic_api: REQUIRED
image_version_ironic_conductor: REQUIRED
image_version_ironic_inspector: REQUIRED
image_version_ironic_pxe: REQUIRED

debug: "True"
db_name: ironic
db_user: ironic
db_password: DEFINE_IN_REGION_CHART

inspector_db_name: ironic_inspector
inspector_db_user: ironic_inspector
inspector_db_password: DEFINE_IN_REGION_CHART

inspector:
  port_internal: '5050'
  dhcp:
    port: '67'
    proxy_port: '4011'
    ip: DEFINE_IN_REGION_CHART
    range: DEFINE_IN_REGION_CHART
    options:
      router: DEFINE_IN_REGION_CHART

tftp_ip: DEFINE_IN_REGION_CHART

port_metrics: '9102'
sentry_dsn: DEFINE_IN_REGION_CHART

network_management_uuid: DEFINE_IN_REGION_CHART
network_cleaning_uuid: DEFINE_IN_REGION_CHART
swift_account: DEFINE_IN_REGION_CHART
swift_tempurl: DEFINE_IN_REGION_CHART

postgres:
  name: ironic

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
            formatter: context
        "null":
            class: logging.NullHandler
            args: "()"
            formatter: default
    loggers:
        root:
            handlers: "null"
            level: WARNING
        ironic:
            handlers: stdout
            level: DEBUG
        amqp:
            handlers: stdout
            level: WARNING
        amqplib:
            handlers: stdout
            level: WARNING
        eventlet.wsgi.server:
            handlers: stdout
            level: INFO
        sqlalchemy:
            handlers: stdout
            level: WARNING
