# Default values for openstack.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
tags:
  barbican: true
  keystone: false
  glance: true
  nova: true
  barbican: true
  cinder: true
  manila: false
  horizon: false
  neutron: false
  designate: false
  ironic: true

global:
  os_release: mitaka

  region: DEFINED-IN-REGION-CHART

  default_availability_zone: nova

  pgbouncer:
    enabled: false

  default_mtu: '9000'

  # TODO change to chart setting
  postgres_port_public: '5432'

  memcached_port_public: '11211'
  memcached_port_metrics: '9150'

  rabbitmq_default_user: openstack
  rabbitmq_admin_user: admin
  rabbitmq_metrics_user: monitoring
  rabbitmq_port_public: '5672'
  rabbitmq_port_management: '15672'
  rabbitmq_port_metrics: '9150'

  rabbitmq_default_pass: null
  rabbitmq_admin_pass: null
  rabbitmq_metrics_pass: null
  rabbit_transient_queues_ttl: 1800

  glance_service_user: glance
  glance_service_password: null

  glance_api_endpoint_protocol_admin: http
  glance_api_endpoint_protocol_internal: http
  glance_api_endpoint_protocol_public: https


  glance_api_port_admin: '9292'
  glance_api_port_internal: '9292'
  glance_api_port_public: '443'

  neutron_service_user: neutron
  neutron_service_password: null

  neutron_api_endpoint_protocol_admin: http
  neutron_api_endpoint_protocol_internal: http
  neutron_api_endpoint_protocol_public: https


  neutron_api_port_admin: '9696'
  neutron_api_port_internal: '9696'
  neutron_api_port_public: '443'

  keystone_api_endpoint_protocol_admin: http
  keystone_api_endpoint_protocol_admin_ext: https
  keystone_api_endpoint_protocol_internal: http
    # Monasca configuration needs the boolean property below for substitution
  keystone_api_endpoint.protocol.internal_ssl: "False"
  keystone_api_endpoint_protocol_public: https


  keystone_api_port_admin: '35357'
  keystone_api_port_admin_ext: '443'
  keystone_api_port_internal: '5000'
  keystone_api_port_public: '443'


   #This is for backward compatibility in Monasca scripts and will be removed
  keystone_endpoint_protocol: http
  keystone_service_domain: Default
  keystone_service_project: service
  keystone_demo_project: demo

  monasca_api_endpoint_protocol_admin: http
  monasca_api_endpoint_protocol_public:  https
  monasca_api_endpoint_protocol_internal: http
  monasca_api_port_admin: '8070'
  monasca_api_port_public: '443'
  monasca_api_port_internal: '8070'

  ironic_service_user: ironic
  ironic_service_password: null

  ironic_api_endpoint_protocol_admin: http
  ironic_api_endpoint_protocol_internal: http
  ironic_api_endpoint_protocol_public: https


  ironic_api_port_admin: '6385'
  ironic_api_port_internal: '6385'
  ironic_api_port_public: '443'

  ironic_pxe_port_public: '69'
  ironic_pxe_endpoint_host_public: DEFINED-IN-REGION-CHART
  ironic_pxe_endpoint_ip_public: DEFINED-IN-REGION-CHART

  nova_service_user: nova
  nova_service_password: null
  nova_metadata_secret: DEFINED-IN-REGION-CHART

  nova_api_endpoint_protocol_admin: http
  nova_api_endpoint_protocol_internal: http
  nova_api_endpoint_protocol_public: https


  nova_api_port_admin: '8774'
  nova_api_port_internal: '8774'
  nova_api_port_public: '443'

  nova_port_metrics: '9102'

  nova_metadata_port_internal: '8775'
  nova_novnc_port_public: '443'
  nova_spicehtml5_port_public: '6082'

  nova_console_endpoint_protocol: https


  barbican_api_endpoint_protocol_admin: http
  barbican_api_endpoint_protocol_internal: http
  barbican_api_endpoint_protocol_public: https
  barbican_api_port_admin: '9311'
  barbican_api_port_internal: '9311'
  barbican_api_port_public: '443'

  cinder_service_user: cinder
  cinder_service_password: null

  cinder_api_endpoint_protocol_admin: http
  cinder_api_endpoint_protocol_internal: http
  cinder_api_endpoint_protocol_public: https

  cinder_api_port_admin: '8776'
  cinder_api_port_internal: '8776'
  cinder_api_port_public: '443'

  horizon_endpoint_port: '8080'


  manila_service_user: manila
  manila_service_password: null
  manila_endpoint_protocol: http
  manila_api_port_public: '8786'

  manila_api_endpoint_protocol_admin: http
  manila_api_endpoint_protocol_internal: http
  manila_api_endpoint_protocol_public: https

  manila_api_port_admin: '8786'
  manila_api_port_internal: '8786'
  manila_api_port_public: '443'

  neutron_service_user: neutron
  neutron_service_password: null

  neutron_api_endpoint_protocol_admin: http
  neutron_api_endpoint_protocol_internal: http
  neutron_api_endpoint_protocol_public: https


  neutron_api_port_admin: '9696'
  neutron_api_port_internal: '9696'
  neutron_api_port_public: '443'

  neutron_manila_physnet: DEFINED-IN-REGION-CHART


  swift_endpoint_protocol: https
  swift_api_port_public: '443'
  swift_api_port_internal: '8080'

  designate_api_endpoint_protocol_admin: http
  designate_api_endpoint_protocol_internal: http
  designate_api_endpoint_protocol_public: https
  designate_api_port_internal: '9001'
  designate_api_port_admin: '9001'
  designate_api_port_public: '443'
  designate_metrics_port: '9102'
  designate_mdns_port_public: '5354'
  designate_mdns_external_ip: DEFINED-IN-REGION-CHART
  designate_service_user: designate
  designate_service_password: null

  barbican_service_user: barbican
  barbican_service_password: null


  keystone_router_api_endpoint_protocol_public: https
  keystone_router_api_port_public: '443'

  lyra_api_endpoint_protocol_public: https
  lyra_api_port_public: '443'

  arc_api_endpoint_protocol_public: https
  arc_api_port_public: '443'

  webcli_api_endpoint_protocol_public: https
  webcli_api_port_public: '443'

  cfm_api_endpoint_protocol_public: https
  cfm_api_port_public: '443'
  cfm_service_password: null

  master_password: null

vcenter_operator:
    username:
    pbm_enabled: "false"

    vcenter_nanny_enabled: False
    vcenter_nanny_debug: True
    # dry run mode, i.e. just pretend to cleanup the entries
    vcenter_nanny_dry_run: true
    # power off machines discovered as orphaned
    vcenter_nanny_power_off: false
    # unregister machines discovered as orphaned
    vcenter_nanny_unregister: false
    # delete machines discovered as orphaned
    vcenter_nanny_delete: false
    # run the db cleanup every n minutes
    vcenter_nanny_interval: 720
    # really delete entities after how many iterations
    vcenter_nanny_iterations: 14
    vcenter_exporter:
      enabled: DEFINED-IN-REGION-CHART
      image_version: DEFINED-IN-REGION-CHART
      listen_port: 9102
      interval: 120
      name_shortening_regex: DEFINED-IN-REGION-CHART
      docker_repo: DEFINED-IN-REGION-CHART

keystone:
  image_version_keystone_m3: DEFINED-IN-REGION-CHART
nova:
  image_version_nova_api: DEFINED-IN-REGION-CHART
  image_version_nova_compute: DEFINED-IN-REGION-CHART
  image_version_nova_libvirt: DEFINED-IN-REGION-CHART
  image_version_nova_conductor: DEFINED-IN-REGION-CHART
  image_version_nova_consoleauth: DEFINED-IN-REGION-CHART
  image_version_nova_novncproxy: DEFINED-IN-REGION-CHART
  image_version_nova_spicehtml5proxy: DEFINED-IN-REGION-CHART
  image_version_nova_scheduler: DEFINED-IN-REGION-CHART

barbican:
  image_version_glance_api: DEFINED-IN-REGION-CHART
  image_version_glance_registry: DEFINED-IN-REGION-CHART
barbican:
  image_version_barbican_m3: DEFINED-IN-REGION-CHART
cinder:
  image_version_cinder_api: DEFINED-IN-REGION-CHART
  image_version_cinder_scheduler: DEFINED-IN-REGION-CHART
  image_version_cinder_volume: DEFINED-IN-REGION-CHART
horizon:
  image_version_horizon_m3: DEFINED-IN-REGION-CHART
manila:
  image_version_manila_api_m3: DEFINED-IN-REGION-CHART
  image_version_manila_scheduler_m3: DEFINED-IN-REGION-CHART
  image_version_manila_share_m3: DEFINED-IN-REGION-CHART
neutron:
  image_version_neutron_server_m3: DEFINED-IN-REGION-CHART
  image_version_neutron_openvswitch_agent: DEFINED-IN-REGION-CHART
  image_version_neutron_vswitchdb: DEFINED-IN-REGION-CHART
  image_version_neutron_vswitchd: DEFINED-IN-REGION-CHART
