apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}-mariadb
  labels:
    system: openstack
    type: database
    component: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{.Values.name}}-mariadb
  template:
    metadata:
      labels:
        app: {{.Values.name}}-mariadb

    spec:
      containers:
      - name: mariadb
        image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value:
            {{.Values.root_password}}
        ports:
          - name: mariadb
            containerPort: 3306
        volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
            readOnly: false
          - name: initdb 
            mountPath: /docker-entrypoint-initdb.d
{{- if .Values.backup.enabled }}
          - name: db-socket
            mountPath: /var/run/mysqld
      - name: backup
        image: {{.Values.backup.repository}}:{{.Values.backup.image_version}}
        imagePullPolicy: IfNotPresent
        env:
          - name: MY_POD_NAME
            value: mysql-backup-{{.Values.name}}
          - name: MY_POD_NAMESPACE
            value: {{.Release.Namespace}}
          - name: OS_AUTH_URL
            value: {{.Values.backup.os_auth_url}}
          - name: OS_AUTH_VERSION
            value: {{.Values.backup.os_auth_version | quote}}
          - name: OS_IDENTITY_API_VERSION
            value: {{.Values.backup.os_identity_api_version | quote}}
          - name: OS_USERNAME
            value: {{.Values.backup.os_username}}
          - name: OS_USER_DOMAIN_NAME
            value: {{.Values.backup.os_user_domain}}
          - name: OS_PROJECT_NAME
            value: {{.Values.backup.os_project_name}}
          - name: OS_PROJECT_DOMAIN_NAME
            value: {{.Values.backup.os_project_domain}}
          - name: OS_REGION_NAME
            value: {{.Values.backup.os_region_name}}
          - name: OS_PASSWORD
            value: {{.Values.backup.os_password | quote}}
          - name: BACKUP_MYSQL_FULL
            value: {{.Values.backup.interval_full | quote}}
          - name: BACKUP_MYSQL_INCR
            value: {{.Values.backup.interval_incr | quote}}
        volumeMounts:
        - mountPath: /db/data
          name: mariadb-persistent-storage
          readOnly: true
        - mountPath: /db/socket
          name: db-socket
{{- end }}
      volumes:
{{- if .Values.persistence_claim }}
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
           claimName: {{.Values.persistence_claim }}
{{- end }}
{{- if .Values.backup.enabled }}
        - name: db-socket
          emptyDir: {}
{{- end }}
{{- if .Values.initdb_configmap }}
        - name: initdb 
          configMap:
            name: {{ .Values.initdb_configmap }}  
{{ end }}
