apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}-mariadb
  labels:
    system: openstack
    type: database
    component: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{.Values.name}}-mariadb
  template:
    metadata:
      labels:
        app: {{.Values.name}}-mariadb

    spec:
      containers:
      - name: mariadb
        image: {{.Values.image}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{.Values.root_password}}
        - name: MY_POD_NAME
          value: mariadb-{{.Values.name}}
        - name: MY_POD_NAMESPACE
          value: {{.Release.Namespace}}
        ports:
          - name: mariadb
            containerPort: 3306
        volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
            readOnly: false
          - name: initdb
            mountPath: /docker-entrypoint-initdb.d
{{- if .Values.backup.enabled }}
          - name: mariadb-socket
            mountPath: /var/run/mysqld
{{- end }}
{{- if .Values.backup.enabled }}
      - image: {.Values.backup.image}}
        name: backup
        env:
        - name: MY_POD_NAME
          value: mariadb-{{.Values.name}}
        - name: MY_POD_NAMESPACE
          value: {{.Release.Namespace}}
        volumeMounts:
        - mountPath: /db/data
          name: mariadb-persistent-storage
        - mountPath: /db/socket
          name: mariadb-socket
        - mountPath: /etc/db-backup
          name: mariadb-backup-config-volume
{{- end }}
      volumes:
{{- if .Values.backup.enabled }}
        - name: mariadb-socket
          emptyDir: {}
        - name: mariadb-backup-config-volume
          configMap:
            name: mariadb-backup-{{.Values.name}}
{{- end }}
{{- if .Values.persistence_claim }}
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
           claimName: {{.Values.persistence_claim }}
{{- end }}
{{- if .Values.initdb_configmap }}
        - name: initdb
          configMap:
            name: {{ .Values.initdb_configmap }}
{{ end }}
