# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  keystone_api_port_admin: '35357'
  keystone_api_port_admin_ext: '443'
  keystone_api_port_internal: '5000'
  keystone_api_port_public: '443'
  pgbouncer:
    enabled: false

pod:
  replicas:
    api: 2
  lifecycle:
    upgrades:
      deployments:
        revision_history: 5
        pod_replacement_strategy: RollingUpdate
        rolling_update:
           max_unavailable: 0
           max_surge: 1

debug: "False"

image_version: null
image_version_keystone: null

port_metrics: '9102'

db_name: keystone
db_user: keystone

db_password: null
admin_token: DEFINED-IN-REGION-CHART

# token_expiration: 3600

bootstrap_user: admin
bootstrap_password: DEFINED-IN-REGION-CHART

sentry_dsn: DEFINED-IN-REGION-CHART

cloud_admin_project: DEFINED-IN-REGION-CHART

cron_schedule: "0 * * * *"

fernet_secrets:
  - DEFINED-IN-REGION-CHART
  - DEFINED-IN-REGION-CHART

pg_metrics:
  name: keystone
  db_name: keystone
  db_user: keystone
  db_password: null

postgres:
  name: keystone
  users:
    keystone: {}

operator:
  sentry_dsn: DEFINED-IN-REGION-CHART
