# Default values for global.postgres_
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  image_namespace: REQUIRED
  image_repository: REQUIRED

name: DEFINED-IN-COMPONENT-CHART
user: postgres
password: DEFINED-IN-REGION-CHART
port_public: '5432'
port_private: '5432'
port_metrics: '9187'
hba_cidr: 0.0.0.0/0

image_version_postgres: '9.4'

persistence:
  enabled: true

backup:
  enabled: false
  image_version: v0.4.2
  interval_full: 3 days
  interval_incr: 3 days
  os_username: db_backup
  os_user_domain: Default
  os_password: DEFINED-IN-REGION-SECRETS
  os_project_name: master
  os_project_domain: ccadmin
